@echo off
echo ANTIVIRUS PROPIO PARA VERIFICAR LAS CONEXIONES ESTABLECIDAS
echo ................
echo ................
netstat -ano | findstr.exe ESTA*
echo ................
echo MAS INFORMACION DE LAS CONEXIONES ESTABLECIDAS
ECHO ................
netstat -b
pause